import secrets
from datetime import UTC, datetime, timedelta
from uuid import UUID, uuid4

from fastapi import HTTPException, status
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import raiseload

from app.core.config import settings
from app.core.redis import get_redis
from app.core.security import (
    create_access_token,
    generate_secure_token,
    hash_password,
    hash_token,
    verify_password,
)
from app.models.user import Device, User, UserPreferences
from app.schemas.auth import (
    DeviceInfo,
    RegisterRequest,
    TokenPair,
    UpdateProfileRequest,
    UpdateSettingsRequest,
    UserOut,
)
from app.services import cache_service

REFRESH_TOKEN_EXPIRE_DAYS = 7
PASSWORD_RESET_TTL_SECONDS = 900


async def set_rls_user(session: AsyncSession, user_id: UUID) -> None:
    """Enables RLS for the rest of this transaction once we already know
    who the user is (e.g. after verifying a password or reset token)."""
    await session.execute(
        text("SELECT set_config('app.current_user_id', :uid, true)"), {"uid": str(user_id)}
    )


def build_user_out(user: User) -> UserOut:
    """UserOut mixes identity (`users`) and preferences (`user_preferences`,
    a separate table -- see migration f2a8c4e1d6b7). `user.preferences` comes
    preloaded via the model's lazy="selectin", no extra query needed."""
    return UserOut(
        id=user.id,
        email=user.email,
        name=user.name,
        avatar_url=user.avatar_url,
        role=user.role,
        auth_provider=user.auth_provider,
        theme=user.preferences.theme,
        locale=user.preferences.locale,
        email_notifications=user.preferences.email_notifications,
        push_notifications=user.preferences.push_notifications,
        pay_cycle=user.preferences.pay_cycle,
        debt_trouble_mode=user.preferences.debt_trouble_mode,
        last_seen_changelog_version=user.preferences.last_seen_changelog_version,
        accepted_disclaimer_version=user.preferences.accepted_disclaimer_version,
        current_disclaimer_version=settings.DISCLAIMER_VERSION,
        created_at=user.created_at,
    )


async def get_user_by_email(session: AsyncSession, email: str) -> User | None:
    """Used only in PRE-authentication contexts (register/login/forgot_password
    here, and the google_auth_service lookup) -- at that point no user_id is
    known yet, so it's impossible to have called set_rls_user() already.
    User.preferences is lazy="selectin" at the model level (loads on its own
    on any User fetch), but that cascading query DOES hit the user_preferences
    RLS policy without app.current_user_id set -- unlike the insert bug in
    register()/resolve_user(), here there's no way to "set RLS earlier"
    because the problem is inside this very function, before the caller can
    do anything. None of this helper's call sites need `.preferences` (they're
    all identity/password checks), so that specific loader is turned off with
    raiseload instead of letting the sub-query fire on its own."""
    result = await session.execute(
        select(User).options(raiseload(User.preferences)).where(User.email == email)
    )
    return result.scalar_one_or_none()


async def register(session: AsyncSession, data: RegisterRequest) -> User:
    if await get_user_by_email(session, data.email):
        raise HTTPException(status.HTTP_409_CONFLICT, "El email ya esta registrado")
    if not data.accept_disclaimer:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "Debes aceptar el aviso de privacidad para crear una cuenta",
        )

    # id generated by hand (don't rely on the column's default=uuid.uuid4):
    # the ORM only applies that default when it flushes the INSERT, so
    # user.id stays None until then -- if None gets passed to
    # set_rls_user() below, `app.current_user_id` ends up set as the
    # string "None" and the user_preferences policy blows up with
    # "invalid input syntax for type uuid" instead of letting the insert through.
    # Same pattern as budget_service (explicit id=uuid4() when the id needs
    # to be known before the flush).
    user = User(
        id=uuid4(),
        email=data.email,
        name=data.name,
        password_hash=hash_password(data.password),
        role="user",
        auth_provider="email",
        preferences=UserPreferences(
            accepted_disclaimer_version=settings.DISCLAIMER_VERSION,
            **({"locale": data.locale} if data.locale else {}),
        ),
    )
    # The cascading insert of UserPreferences (FORCE ROW LEVEL SECURITY, see
    # migration 293528f67338) needs app.current_user_id set to pass its
    # policy -- without this, registration broke with "new row violates
    # row-level security policy for table user_preferences" on any role
    # other than superuser/BYPASSRLS (not visible locally because the app's
    # role there is superuser, but it was on a real Postgres -- bug
    # reported on the first real deploy).
    await set_rls_user(session, user.id)
    session.add(user)
    await session.flush()
    return user


async def issue_tokens_for_device(
    session: AsyncSession, user: User, device: DeviceInfo
) -> TokenPair:
    """Shared by `login()` (email/password) and the Google OAuth callback
    (extended M01) -- both end up with the same token pair +
    registration/update of the `Device`, the only difference between them is
    HOW `user` was resolved before getting here."""
    await set_rls_user(session, user.id)

    refresh_token = generate_secure_token()
    expires_at = datetime.now(UTC) + timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)

    existing = await session.execute(
        select(Device).where(
            Device.user_id == user.id,
            Device.device_type == device.device_type,
            Device.device_name == device.device_name,
        )
    )
    device_row = existing.scalar_one_or_none()
    if device_row:
        device_row.refresh_token = hash_token(refresh_token)
        device_row.refresh_token_expires_at = expires_at
        device_row.push_token = device.push_token or device_row.push_token
        device_row.last_used_at = datetime.now(UTC)
        device_row.is_active = True
    else:
        session.add(
            Device(
                user_id=user.id,
                device_name=device.device_name,
                device_type=device.device_type,
                push_token=device.push_token,
                refresh_token=hash_token(refresh_token),
                refresh_token_expires_at=expires_at,
                last_used_at=datetime.now(UTC),
                is_active=True,
            )
        )

    access_token = create_access_token(user.id, user.role)
    return TokenPair(access_token=access_token, refresh_token=refresh_token)


async def login(session: AsyncSession, email: str, password: str, device: DeviceInfo) -> TokenPair:
    redis = await get_redis()
    if await cache_service.is_login_locked(redis, email):
        raise HTTPException(
            status.HTTP_429_TOO_MANY_REQUESTS,
            "Demasiados intentos fallidos. Espera unos minutos e intenta de nuevo.",
        )

    user = await get_user_by_email(session, email)
    if user is None or user.password_hash is None:
        await cache_service.register_failed_login(redis, email)
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Usuario o contraseña incorrectos")
    if not verify_password(password, user.password_hash):
        await cache_service.register_failed_login(redis, email)
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Usuario o contraseña incorrectos")
    if not user.is_active:
        raise HTTPException(status.HTTP_403_FORBIDDEN, "Cuenta desactivada")

    await cache_service.clear_failed_logins(redis, email)
    return await issue_tokens_for_device(session, user, device)


async def refresh(session: AsyncSession, refresh_token: str) -> TokenPair:
    """Rotates the refresh token on every use (single-use): the row in
    `devices` only stores its hash (see hash_token), so the comparison is
    also by hash. Returns the new refresh token in plaintext to the client --
    this function used to rotate it in the DB but only returned the new
    access_token, so the client kept sending the old (already invalid)
    refresh token on the next refresh and ended up logged out without
    warning every ~2x ACCESS_TOKEN_EXPIRE_MINUTES; see api.ts in the frontend.

    Bug #4 of the RLS family: this is the ONLY Device lookup that can't know
    the user_id ahead of time (it's literally the endpoint used when the
    access token has already expired) -- rls_devices (see migration
    a3d7af2c6426) has a separate clause for this, enabled by setting
    app.lookup_refresh_token to the hash being looked up before the query.
    logout()/logout_all() don't need this: they already know the user_id
    from a valid access token before touching `devices`."""
    hashed = hash_token(refresh_token)
    await session.execute(
        text("SELECT set_config('app.lookup_refresh_token', :t, true)"), {"t": hashed}
    )
    result = await session.execute(select(Device).where(Device.refresh_token == hashed))
    device = result.scalar_one_or_none()
    if device is None or not device.is_active:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Sesion invalida")
    if device.refresh_token_expires_at and device.refresh_token_expires_at < datetime.now(UTC):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Sesion expirada")

    user_result = await session.execute(select(User).where(User.id == device.user_id))
    user = user_result.scalar_one_or_none()
    if user is None or not user.is_active:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Sesion invalida")

    await set_rls_user(session, user.id)
    new_refresh_token = generate_secure_token()
    device.refresh_token = hash_token(new_refresh_token)
    device.refresh_token_expires_at = datetime.now(UTC) + timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)
    device.last_used_at = datetime.now(UTC)

    access_token = create_access_token(user.id, user.role)
    return TokenPair(access_token=access_token, refresh_token=new_refresh_token)


async def logout(session: AsyncSession, user_id: UUID, refresh_token: str) -> None:
    await set_rls_user(session, user_id)
    result = await session.execute(
        select(Device).where(
            Device.refresh_token == hash_token(refresh_token), Device.user_id == user_id
        )
    )
    device = result.scalar_one_or_none()
    if device:
        device.is_active = False
        device.refresh_token = None


async def logout_all(session: AsyncSession, user_id: UUID) -> None:
    await set_rls_user(session, user_id)
    result = await session.execute(select(Device).where(Device.user_id == user_id))
    for device in result.scalars():
        device.is_active = False
        device.refresh_token = None


async def change_password(
    session: AsyncSession, user_id: UUID, current_password: str, new_password: str
) -> None:
    result = await session.execute(select(User).where(User.id == user_id))
    user = result.scalar_one()
    if user.password_hash is None or not verify_password(current_password, user.password_hash):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Password actual incorrecto")
    user.password_hash = hash_password(new_password)


async def forgot_password(session: AsyncSession, email: str) -> None:
    user = await get_user_by_email(session, email)
    if user is None or user.password_hash is None:
        return  # Don't reveal whether the email exists or is an OAuth account

    token = secrets.token_urlsafe(32)
    redis = await get_redis()
    await redis.set(f"pwd_reset:{token}", str(user.id), ex=PASSWORD_RESET_TTL_SECONDS)
    # Phase 4 (pending, see Notion): without a real email provider connected
    # (app.tasks.email.send_email is a stub that just logs), the token never
    # reaches the user -- and the frontend doesn't expose a "forgot my
    # password" screen calling this endpoint yet either. The backend is ready
    # (token + /auth/reset-password work end to end) for when a real provider
    # is connected; still missing that provider and the frontend screen.


async def reset_password(session: AsyncSession, token: str, new_password: str) -> None:
    redis = await get_redis()
    redis_key = f"pwd_reset:{token}"
    user_id_raw = await redis.get(redis_key)
    if not user_id_raw:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Token invalido o expirado")

    user_id = UUID(user_id_raw)
    result = await session.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    if user is None:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Token invalido o expirado")

    user.password_hash = hash_password(new_password)
    await redis.delete(redis_key)
    await logout_all(session, user.id)


async def update_profile(session: AsyncSession, user_id: UUID, data: UpdateProfileRequest) -> User:
    result = await session.execute(select(User).where(User.id == user_id))
    user = result.scalar_one()
    for field, value in data.model_dump(exclude_unset=True).items():
        setattr(user, field, value)
    await session.flush()
    return user


async def update_settings(
    session: AsyncSession, user_id: UUID, data: UpdateSettingsRequest
) -> User:
    result = await session.execute(select(User).where(User.id == user_id))
    user = result.scalar_one()
    for field, value in data.model_dump(exclude_unset=True).items():
        setattr(user.preferences, field, value)
    await session.flush()
    return user


async def accept_disclaimer(session: AsyncSession, user_id: UUID) -> User:
    """Unlike update_settings, this does NOT accept the value from the
    client -- the server itself stamps it with settings.DISCLAIMER_VERSION.
    It's a compliance field (DisclaimerGate blocks the whole app until it
    matches), not a UI preference like last_seen_changelog_version."""
    result = await session.execute(select(User).where(User.id == user_id))
    user = result.scalar_one()
    user.preferences.accepted_disclaimer_version = settings.DISCLAIMER_VERSION
    await session.flush()
    return user


async def unlink_google(session: AsyncSession, user_id: UUID) -> User:
    result = await session.execute(select(User).where(User.id == user_id))
    user = result.scalar_one()
    if user.google_id is None:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Esta cuenta no esta vinculada a Google")
    if user.password_hash is None:
        raise HTTPException(
            status.HTTP_400_BAD_REQUEST,
            "No puedes desvincular Google: es tu unica forma de entrar a la cuenta",
        )
    user.google_id = None
    user.auth_provider = "email"
    await session.flush()
    return user


async def delete_account(session: AsyncSession, user_id: UUID, password: str | None) -> None:
    """Soft delete (deleted_at), doesn't remove the row -- same pattern as
    accounts/categories/debts. Revokes all active sessions. Asks for the
    current password as confirmation only if the user has one (Google-only
    accounts have nothing to verify here)."""
    result = await session.execute(select(User).where(User.id == user_id))
    user = result.scalar_one()
    if user.password_hash is not None:
        if not password or not verify_password(password, user.password_hash):
            raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Contraseña incorrecta")

    await logout_all(session, user.id)
    user.is_active = False
    user.deleted_at = datetime.now(UTC)


async def register_device(session: AsyncSession, user_id: UUID, device: DeviceInfo) -> Device:
    await set_rls_user(session, user_id)
    existing = await session.execute(
        select(Device).where(
            Device.user_id == user_id,
            Device.device_type == device.device_type,
            Device.device_name == device.device_name,
        )
    )
    device_row = existing.scalar_one_or_none()
    if device_row:
        device_row.push_token = device.push_token
        device_row.last_used_at = datetime.now(UTC)
        return device_row

    device_row = Device(
        user_id=user_id,
        device_name=device.device_name,
        device_type=device.device_type,
        push_token=device.push_token,
        last_used_at=datetime.now(UTC),
    )
    session.add(device_row)
    await session.flush()
    return device_row


async def list_devices(session: AsyncSession, user_id: UUID) -> list[Device]:
    await set_rls_user(session, user_id)
    result = await session.execute(
        select(Device).where(Device.user_id == user_id, Device.is_active.is_(True))
    )
    return list(result.scalars().all())


async def revoke_device(session: AsyncSession, user_id: UUID, device_id: UUID) -> None:
    await set_rls_user(session, user_id)
    result = await session.execute(
        select(Device).where(Device.id == device_id, Device.user_id == user_id)
    )
    device = result.scalar_one_or_none()
    if device is None:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Dispositivo no encontrado")
    device.is_active = False
    device.refresh_token = None
