from uuid import uuid4

import httpx
from fastapi import HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.models.user import User, UserPreferences
from app.services import auth_service

GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_URL = "https://www.googleapis.com/oauth2/v3/userinfo"


async def exchange_code(code: str) -> dict:
    """Exchanges the one-time `code` for the user's Google profile. Two
    direct HTTP calls via httpx -- no need for authlib for this, the real
    flow is two plain POST/GET calls."""
    async with httpx.AsyncClient(timeout=10.0) as client:
        token_response = await client.post(
            GOOGLE_TOKEN_URL,
            data={
                "code": code,
                "client_id": settings.GOOGLE_CLIENT_ID,
                "client_secret": settings.GOOGLE_CLIENT_SECRET,
                "redirect_uri": settings.GOOGLE_REDIRECT_URI,
                "grant_type": "authorization_code",
            },
        )
        if token_response.status_code != 200:
            raise HTTPException(
                status.HTTP_400_BAD_REQUEST, "No se pudo validar el codigo de Google"
            )
        google_access_token = token_response.json()["access_token"]

        userinfo_response = await client.get(
            GOOGLE_USERINFO_URL,
            headers={"Authorization": f"Bearer {google_access_token}"},
        )
        if userinfo_response.status_code != 200:
            raise HTTPException(
                status.HTTP_400_BAD_REQUEST, "No se pudo obtener el perfil de Google"
            )
        return userinfo_response.json()


async def resolve_user(session: AsyncSession, google_user: dict) -> tuple[User, bool]:
    """Three cases: already linked (direct login), existing email not yet
    linked (gets linked silently -- can now log in with either method from
    now on), or new user (no password, can only log in via Google). Rejects
    an email not verified by Google in any case.

    The tuple's second element is `is_new` -- the router sends it as a
    query param to the frontend (`&is_new=1`) so AuthCallback marks the
    changelog as seen on newly created accounts (see ChangelogButton.tsx);
    without this a freshly created Google account would see the "What's
    new" modal on its first login, same issue that was fixed for email
    registration."""
    if not google_user.get("email_verified", False):
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "El email de Google no esta verificado")

    sub = google_user["sub"]
    email = google_user["email"]
    name = google_user.get("name") or email.split("@")[0]
    picture = google_user.get("picture")

    result = await session.execute(select(User).where(User.google_id == sub))
    user = result.scalar_one_or_none()
    if user is not None:
        # Only autofills if the user never set a picture of their own -- we
        # don't overwrite one they uploaded by hand in Settings.
        if user.avatar_url is None and picture:
            user.avatar_url = picture
            await session.flush()
        return user, False

    user = await auth_service.get_user_by_email(session, email)
    if user is not None:
        user.google_id = sub
        if user.avatar_url is None and picture:
            user.avatar_url = picture
        await session.flush()
        return user, False

    # id generated by hand -- see the long comment in auth_service.register:
    # the column's default=uuid.uuid4 only applies on flush, so user.id
    # would still be None if we passed it to set_rls_user before the insert
    # without generating it ourselves first.
    user = User(
        id=uuid4(),
        email=email,
        name=name,
        avatar_url=picture,
        password_hash=None,
        role="user",
        auth_provider="google",
        google_id=sub,
        is_active=True,
        preferences=UserPreferences(),
    )
    # Same fix as auth_service.register(): the cascading insert of
    # UserPreferences needs app.current_user_id set to pass its RLS policy
    # (FORCE ROW LEVEL SECURITY).
    await auth_service.set_rls_user(session, user.id)
    session.add(user)
    await session.flush()
    return user, True
